### ISSUE TITLE
feedback from project site

### ISSUE THREAD

**Issue by martinohanlon** [raspberrypilearning/build-your-own-weather-station#14]
The ground link at the bottom left (connecting the RJ11 breakout board for the rain gauge) is incorrectly placed. The rain gauge uses the center 2 pins, 3 and 4. Your wiring has GPIO 6 grounded and the other side of the rain gauge is not connected to anything.

@topshed - did you want to look at this?

**Comment by topshed** [comment]
I'll take a look

**Comment by topshed** [comment]
yep, this is a mistake. Updated diagrams now live
