### ISSUE TITLE
Confusion with the voltage divider

### ISSUE THREAD

**Issue by VicenteYago** [raspberrypilearning/build-your-own-weather-station#21]
Hi, originally I opened a post in the forum, but I decided to expand the content here for convenience, here is the link: https://www.raspberrypi.org/forums/viewtopic.php?f=112&t=278466
I also made feedback submission through the station's own guide, sorry if you receive this problem through various channels.

Let's get to the problem:
In the official guide, concretely in this link: https://projects.raspberrypi.org/en/projects/build-your-own-weather-station/7

the concept of voltage divider is presented, and then the following equation is written:

![Screenshot from 2020-06-27 13-39-32](https://user-images.githubusercontent.com/16523144/85921542-42d68800-b87d-11ea-8742-3888f01b4d5c.png)

but then, in the clue code it's written like this:
![Screenshot from 2020-06-27 13-52-59](https://user-images.githubusercontent.com/16523144/85921593-89c47d80-b87d-11ea-8cd5-e5b94c5028e8.png)

Obviously the equations are not equivalent, and according to the literature the correct one is the first.

But, lets go deeper in my confusion: the voltage divider its used to measure the output voltage from the wind vane in order to get an angle that indicates where the wind is coming from, using in the process an analog to digital converter. In the datasheet you can see the following table:
![Screenshot from 2020-06-27 14-20-32](https://user-images.githubusercontent.com/16523144/85930472-eb580c80-b8bc-11ea-9a19-b8b325c4102a.png)

In the diagram, the external resistance is R1 (10 k) and the inner variable resistance offered by the  wind vane internals is R2. 

Guided by my curiosity i decided to replicate the table output voltage (right column) with this python code  from the file vane_values.py (with the corrected equation in the numerator)

```{python}
resistances = [33000, 6570, 8200, 891,
              1000, 688, 2200, 1410,
              3900, 3140, 16000, 14120,
              120000, 42120, 64900, 21880]


def voltage_divider(r1, r2, vin):
        vout = (vin*r2)/(r1+r2) # in the guide its written: (vin*r1)/(r1+r2) 
        return round(vout, 3)

for x in range(len(resistances)):
    print("  5V",resistances[x], voltage_divider(10000,resistances[x], 5.0))
```

```{bash}
  5V 33000 3.837
  5V 6570 1.982
  5V 8200 2.253
  5V 891 0.409
  5V 1000 0.455
  5V 688 0.322
  5V 2200 0.902
  5V 1410 0.618
  5V 3900 1.403
  5V 3140 1.195
  5V 16000 3.077
  5V 14120 2.927
  5V 120000 4.615
  5V 42120 4.041
  5V 64900 4.332
  5V 21880 3.432
```
and the result agrees with the datasheet. 

Back to the guide it is justified that for the voltage divider, in the case of the raspberry you have to use vin = 3.3 and R1 = 4.7 kohms, so if we modify the code above accordingly:

```{python}
    print("  3.3V",resistances[x], voltage_divider(4700,resistances[x], 3.3))
```
```{bash}
3.3V 33000 2.889
3.3V 6570 1.924
3.3V 8200 2.098
3.3V 891 0.526
3.3V 1000 0.579
3.3V 688 0.421
3.3V 2200 1.052
3.3V 1410 0.762
3.3V 3900 1.497
3.3V 3140 1.322
3.3V 16000 2.551
3.3V 14120 2.476
3.3V 120000 3.176
3.3V 42120 2.969
3.3V 64900 3.077
3.3V 21880 2.716
```

And we have come to the bottom of the problem: those values are not the ones proposed in the solutions:

![Screenshot from 2020-06-27 22-22-19](https://user-images.githubusercontent.com/16523144/85931440-c36ca700-b8c4-11ea-860d-588a942918f9.png)

![Screenshot from 2020-06-27 22-22-41](https://user-images.githubusercontent.com/16523144/85931459-d3848680-b8c4-11ea-96d3-006f91c9780c.png)

I have not researched further, but I believe that if I have not mistaken any step, the wind directions measured by this sensor and official code would actually be incorrect, because of the failure of the voltage divider equation. 

What do you think about this?
I'm really learning about electronics and I wanted to make sense of what I was doing. 

 Thank you very much.

**Comment by jrcalvert** [comment]
Hello,
Yes, I came to a similar conclusion just yesterday when trying to get the voltage array values to agree with the guide.
I think it might be that the circuit being used shows the output (input to the ADC) has the resister connecting to Ground and Not 5v, so the voltage divider is the opposite way arount, i.e. R1 = wind-vane, R2 = 4.7K.
I'm not sure, but that's my current reasoning!

Jason

**Comment by VicenteYago** [comment]
Yes!, if you switch the resistor values all makes sense. 
Thanks for the up, i forgot to update this issue, with this info. 

I think this is solved, im closing if nobody opposes.
