### ISSUE TITLE
Feedback from project site

### ISSUE THREAD

**Issue by martinohanlon** [raspberrypilearning/build-your-own-weather-station#6]
URL: /en/projects/build-your-own-weather-station/ Hi, I'd like to print out the project "Build your own weather station", but all that happens when I press the 'print' button on your page is the browser refreshes to a blank page. Also - If I accidentally go to the 'all projects' list, I can't find the build your own weather station one under either 'weather' or 'python'

**Comment by MarcScott** [comment]
I think this might be one for @aldreth

**Comment by MarcScott** [comment]
I've shifted this issue to https://github.com/RaspberryPiFoundation/projects-ui/issues/1169 and am now closing
